version: "3.9"

volumes:
  wordpress:
    name: wp-data
    driver: local
    driver_opts:
      device: ${WP_PATH}
      o: bind
      type: none
  mariadb:
    name: sql-data
    driver: local
    driver_opts:
      device: ${BBDD_PATH}
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
    
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    environment:
      MYSQL_HOST:       mariadb
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      MYSQL_USER:       ${MYSQL_USER}
      MYSQL_PASSWORD:   ${MYSQL_PASSWORD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_EMAIL:         ${WP_EMAIL}
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        MYSQL_DATABASE:   ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  
  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp
    ports:
      - "20:20"
      - "21:21"
      - "1200-1210:1200-1210"
    volumes:
      - wordpress:/var/www/html
    environment:
      FTP_USER:       ${FTP_USER}
      FTP_PASSWORD:   ${FTP_PASSWORD}
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    ports:
      - "8080:80"
    environment:
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb