version: "3.9"

volumes:
  wordpress:
    # name: wp-files
    # driver: local
    # command:
    #  [ "mkdir", "-p", "/home/ubuntu/deploy/inception/srcs/dev_data" ]
    # driver_opts:
    #   device: /home/ubuntu/deploy/inception/srcs/dev_data
    #   o: bind
    #   type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/.
    ports:
     - "2323:2323"
    volumes:
     - wordpress:/var/www/html
    command: 
     [ "nginx", "-g", "daemon off;" ]
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
    
  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/.
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    #depends_on:
      #- mariadb