version: "3.9"

volumes:
  wordpress:
    name: wp-data
    driver: local
    driver_opts:
      device: /home/ubuntu/deploy/inception/data/wp
      o: bind
      type: none
  mariadb:
    name: sql-data
    driver: local
    driver_opts:
      device: /home/ubuntu/deploy/inception/data/bbdd
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env