version: "3.5"

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/.
    ports:
     - "80:80"
    volumes:
     - ./wordpress:/var/www/html
    command: 
     [ "nginx", "-g", "daemon off;" ]
    env_file:
     - .env
    networks:
     - inception
    #restart: always
    # depends_on:
    #  - wordpress
    
  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/.
    expose:
     - "9000"
    volumes:
     - ./wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
    #depends_on:
     #- mariadb