version: "3.9"

volumes:
  wordpress:
    name: wp-data
  mariadb:
    name: sql-data

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=my_ddbb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env