version: "3.9"

volumes:
  wordpress:
    name: wp-data
    driver: local
    driver_opts:
      device: /home/ubuntu/deploy/inception/data/wp
      o: bind
      type: none
  mariadb:
    name: sql-data
    driver: local
    driver_opts:
      device: /home/ubuntu/deploy/inception/data/bbdd
      o: bind
      type: none

networks:
  inception:
    name: inception
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - wordpress:/var/www/html
    env_file:
     - .env
    networks:
     - inception
    restart: always
    depends_on:
     - wordpress
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      MYSQL_HOST:       mariadb
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      MYSQL_USER:       ${MYSQL_USER}
      MYSQL_PASSWORD:   ${MYSQL_PASSWORD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_EMAIL:         ${WP_EMAIL}
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE:   ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env